# Generated by Django 5.0.6 on 2024-07-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0008_alter_hosts_host_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlans',
            old_name='vlan_nombre',
            new_name='vlan_name',
        ),
    ]
