# Generated by Django 5.0.6 on 2024-07-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0009_rename_vlan_nombre_vlans_vlan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorresOps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operadores_ops', models.CharField(max_length=60)),
                ('team_ops', models.CharField(max_length=60)),
                ('contacto_ops', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='owners',
            old_name='contacto',
            new_name='contacto_form',
        ),
        migrations.RenameField(
            model_name='owners',
            old_name='proyecto',
            new_name='proyecto_form',
        ),
        migrations.RenameField(
            model_name='owners',
            old_name='resposables',
            new_name='resposables_form',
        ),
    ]
