# Generated by Django 5.0.6 on 2024-07-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0010_torresops_rename_contacto_owners_contacto_form_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owners',
            old_name='contacto_form',
            new_name='contacto_own',
        ),
        migrations.RenameField(
            model_name='owners',
            old_name='proyecto_form',
            new_name='proyecto_own',
        ),
        migrations.RenameField(
            model_name='owners',
            old_name='resposables_form',
            new_name='resposables_own',
        ),
    ]
