# Generated by Django 5.0.6 on 2024-07-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0011_rename_contacto_form_owners_contacto_own_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owners',
            old_name='resposables_own',
            new_name='responsables_own',
        ),
    ]
