# Generated by Django 5.0.6 on 2024-07-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0012_rename_resposables_own_owners_responsables_own'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlans',
            old_name='vlan_desc',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='vlans',
            old_name='vlan_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='vlans',
            old_name='vlan_tag',
            new_name='vlan_TAG',
        ),
    ]
