# Generated by Django 5.0.6 on 2024-07-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0013_rename_vlan_desc_vlans_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owners',
            old_name='contacto_own',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='owners',
            old_name='proyecto_own',
            new_name='proyecto',
        ),
        migrations.RenameField(
            model_name='owners',
            old_name='responsables_own',
            new_name='responsables',
        ),
        migrations.RenameField(
            model_name='torresops',
            old_name='contacto_ops',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='torresops',
            old_name='operadores_ops',
            new_name='operadores',
        ),
        migrations.RenameField(
            model_name='torresops',
            old_name='team_ops',
            new_name='team',
        ),
    ]
